### ISSUE TITLE
blockipedia/config/routes.rb

### ISSUE THREAD

**Issue by SageBeard** [SageBeard/blockipedia#1]
Once I sign-up I have a routing error for new user registration:  "No route matches [GET] "/users"
I set up my new & create user in the registration controller, and I'm not sure how to route so the user is created.
````
Rails.application.routes.draw do
  devise_scope :user do
    get 'Sign Up', to: 'devise/registrations#new'
  end

  get 'welcome/index'

  root 'welcome#index'

end
````

**Comment by bdougie** [comment]
If you run rake routes, then /users will not show. You might need to [add the following](https://github.com/SageBeard/bloccit/blob/master/config/routes.rb#L16) to your routes
