### ISSUE TITLE
Navbar not reflecting downgrade

### ISSUE THREAD

**Issue by bdougie** [SageBeard/blockipedia#8]
@SageBeard can you explain more about what you are seeing? 

I am also curious why "premium" is lower case and "Standard" is not here: https://github.com/SageBeard/blockipedia/blob/7-stripe/app/views/devise/registrations/edit.html.erb#L40

**Comment by SageBeard** [comment]
I have the User Type displayed on the navbar. When I have them downgrade their membership, the navbar isn't being reflected. 
````
              <p class="navbar-text"> User Type: <strong> <%= current_user.role %> </strong> </p>
````

Just a typo on premium & standard ...

**Comment by bdougie** [comment]
Does it show when you refresh the page, like "cmd + r"?
